server:
  port: 8860


spring:
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册(The bean 'hiddenHttpMethodFilter', defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/cloud/gateway/config/GatewayAutoConfiguration.class] and overriding is disabled)
  application:
    name: zy-elastic-job

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&serverTimezone=GMT
    username: zhaoyin
    password: Zy999999
  jpa:
    show-sql: true

regCenter:
  serverList: localhost:2181

# redis start
redis:
  #本地装一个,地址通用
  host: 127.0.0.1
  port: 6379
  timeout: 3000
  password:
  # 最大活动对象数
  maxTotal: 1000
  #最大能够保持idel状态的对象数
  maxIdle: 100
  #最小能够保持idel状态的对象数
  minIdle: 50
  #当池内没有返回对象时，最大等待时间
  maxWaitMillis: 10000
  #当调用borrow Object方法时，是否进行有效性检查
  testOnBorrow: true
  #当调用return Object方法时，是否进行有效性检查
  testOnReturn: true
  #“空闲链接”检测线程，检测的周期，毫秒数。如果为负值，表示不运行“检测线程”。默认为-1.
  timeBetweenEvictionRunsMillis: 30000

# redis end